language: cpp

os:
  - osx

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test

packages:
  - libboost1.55-all-dev

compiler:
  - clang

install:
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo apt-get install software-properties-common ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo apt-get install -y make ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo apt-get install libboost1.55-all-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo apt-get install python-sphinx ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo apt-get install gcc-4.8 g++-4.8 ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20 ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20 ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo update-alternatives --config gcc ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo update-alternatives --config g++ ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo pip install --upgrade pip ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then sudo pip install sphinx_rtd_theme ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then export PATH=/usr/local/bin:$PATH ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then brew install boost155 ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then export BOOST_LIBRARYDIR=/usr/local/lib/boost ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then export BOOST_INCLUDEDIR=/usr/local/opt/boost155/include ; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then sudo pip install sphinx; fi
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade pyopenssl
  - sudo pip install sphinx_rtd_theme

script:
  - sudo git submodule sync
  - sudo git submodule update --init
  - uname -a
  - cmake --version
  - make --version
  - clang++ --version
  - g++ --version
  - python --version
  - sphinx-build --version
  - make -C libs full=1
  - make full=1 travis_ci=1
